const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image: '/images/p1.jpg',
            price:120,
            brand:'Nike', 
            Rating:4.5,
            numReviews:10,
            description: 'high quality product',  
        },
        {
            _id:'2',
            name:'Adidas Fit shirt',
            category:'Shirts',
            image: '/images/p1.jpg',
            price:100,
            brand:'Adidas', 
            Rating:4.0,
            numReviews:10,
            description: 'high quality product',  
        },
        {
            _id:'3',
            name:'Lacoste free shirt',
            category:'Shirts',
            image: '/images/p1.jpg',
            price:220,
            brand:'Lacoste', 
            Rating:4.8,
            numReviews:17,
            description: 'high quality product',  
        },
        {
            _id:'4',
            name:'Nike Slim Pants',
            category:'Pants',
            image: '/images/p1.jpg',
            price:78,
            brand:'Nike', 
            Rating:4.5,
            numReviews:14,
            description: 'high quality product',  
        },
        {
            _id:'5',
            name:'Puma Slim Pants',
            category:'Pants',
            image: '/images/p1.jpg',
            price:65,
            brand:'Puma', 
            Rating:4.5,
            numReviews:10,
            description: 'high quality product',  
        },
        {
            _id:'6',
            name:'Adidas slim pants',
            category:'Pants',
            image: '/images/p1.jpg',
            price:139,
            brand:'Adidas', 
            Rating:4.5,
            numReviews:15,
            description: 'high quality product',  
        },

    ],       

};

export default data
